### ISSUE TITLE
Extend to Nd distributions?

### ISSUE THREAD

**Issue by jamesgrogers** [pgromano/pinky#2]
Would this module be extendable to 3D (or ND) distributions?

**Comment by pgromano** [comment]
The methodology is really limited to 2D images. I'd imagine a Brite force application could be done for 3D but it would most likely scale poorly. 

Let me think about this and see if there's an immediate solution. I haven't worked on this package in several years 😅

**Comment by pgromano** [comment]
Hey @jgr1996 , here's a really lazy implementation. It'll go through and sample the indices for the data set `X` at some size `n`. I've only tested it on 2D and 3D images, it should extend to an arbitrary size. 

It's going to assume that the values of the input data `X` are all positive values. Hopefully this helps for your needs?

```python
class Sampler:
    def __init__(self, random_state=None):
        self.random_state = random_state
        
    def sample(self, X, n):
        
        if isinstance(self.random_state, np.random.RandomState):
            sampler = self.random_state.choice
        else:
            sampler = np.random.RandomState(self.random_state).choice
        
        original_shape = X.shape
        p = X.ravel() / X.sum()
        
        ind = sampler(np.prod(original_shape), p=p, size=n)
        return np.array(np.unravel_index(ind, original_shape))
```

**Comment by pgromano** [comment]
[Here](https://gist.github.com/pgromano/1813ee29fb918fae3341c52a305f7fc2) are some examples sampling from image data, I used this adorable puppy

# Original Image
![puppy](https://user-images.githubusercontent.com/12770968/89109202-c8150580-d404-11ea-84d5-9f176ce12cdc.jpeg)

# Comparison to Sampled Image
![sampled_puppy](https://user-images.githubusercontent.com/12770968/89109267-34900480-d405-11ea-9f59-399b45e8a756.jpeg)

**Comment by jamesgrogers** [comment]
Hi @pgromano, thank you for taking the time to write this script. The specific task I'm using pinky for is sampling N points from a 3D probability density function (PDF) defined on a grid. The above example appears to randomly sample grid indices, which is a slightly different output to what I need. In other words, could this code be used to output a set of N coordinates in a Nx3 array drawn from a 3D PDF defined on a MxMxM grid. In the original version of Pinky you have written, it would look something like what I have written below. This only works in 2D however, which is why I asked the original question.

Thank you so much!

````
resampler = Pinky(P=PDF, extent=np.array([xmin,xmax,ymin,ymax]),bins=M)
samples = resampler.sample(n_samples=N)

**Comment by pgromano** [comment]
So I have tested using this on 3D cases as well and it does work. It may not have been obvious, but the image I showed above *is a 3D array* as it has color channels for red, blue, and green. So the fact that not only does the image of the puppy but the _color of the image_ reproduce means that it is successfully sampling from a 3D distribution.

The sampling is (as you point out) grabbing just the indices, but note that the value of the input data is what defines the probability of sampling (which is very similar to what the original version of pinky for 2D cases without interpolation). If you have an `Nx3` array, you can make the output histogram with `np.histogramdd` and feed that in as the input data to the sampler method shown above. 

You can get the values of the indices by taking the same approach used in the pinky code which is to map the indices to a linear array `np.linspace(xmin, xmax, bins=M), np.linspace(ymin, ymax, bins=M)`. If you'd like values slightly outside of the bin values you can use the method from [`add_noise` ](https://github.com/pgromano/pinky/blob/master/pinky/stats/_sample.py#L65) which samples from a normal distribution about the value using the variance from the input data.
