### ISSUE TITLE
Samples restricted to [0, 1] range?

### ISSUE THREAD

**Issue by Gabriel-p** [pgromano/pinky#3]
First of all, thank you for sharing this code.

I'm trying to sample from `func()` defined below. I set up a range in [-10,10] for both dimensions but I only get samples in the [0, 1] range.

What am I missing here?

![Captura de pantalla de 2020-08-31 19-07-02](https://user-images.githubusercontent.com/6054951/91773452-304e3700-ebbd-11ea-8183-27f9a656accd.png)

```

import numpy as np
from matplotlib import patches as mpatches
import matplotlib.pyplot as plt
from pinky import Pinky

# Define some constants
rc, rt, ecc = 2, 10, .85
c1 = 1 / rc**2
c2 = 1 - ecc**2
c3 = -np.sqrt(1 + (rt / rc)**2)
print(c1, c2, c3)


def func(x, y):
    return (np.sqrt(1 + c1 * (x**2 + (y**2 / c2))) + c3)**2


x = np.linspace(-10, 10, 50)
y = np.linspace(-10, 10, 50)
print(x)
XX, YY = np.meshgrid(x, y)

P = func(XX, YY)
p = Pinky(P=P)
sampled_points = p.sample(1000)

ax = plt.subplot(111)
plt.scatter(XX, YY)
plt.scatter(*sampled_points.T)

height = rt * np.sqrt(1. - ecc**2)
ellipse = mpatches.Ellipse(
    xy=(0., 0.), width=2. * rt, height=2. * height,
    facecolor='None', edgecolor='black', linewidth=2,
    transform=ax.transData, zorder=6)
ax.add_patch(ellipse)
plt.xlim(-11, 11)
plt.ylim(-11, 11)
plt.show()
```

**Comment by pgromano** [comment]
Yeah, this is really old code, which I unfortunately wrote terribly vague!

In short, it's not in any documentation or even referenced outside the [actual code](https://github.com/pgromano/pinky/blob/master/pinky/api.py#L7) but there's an `intent` field that you can pass `[-10, 10, -10, 10]` (`xmin, xmax, ymin, ymax`) and it'll give the output in the extent range you want.

It's been several years since I've maintained this project... maybe I'll actually refactor the code for something cleaner 😅

**Comment by pgromano** [comment]
```python
import numpy as np
from matplotlib import patches as mpatches
import matplotlib.pyplot as plt
from pinky import Pinky

# Define some constants
rc, rt, ecc = 2, 10, .85
c1 = 1 / rc**2
c2 = 1 - ecc**2
c3 = -np.sqrt(1 + (rt / rc)**2)
print(c1, c2, c3)


def func(x, y):
    return (np.sqrt(1 + c1 * (x**2 + (y**2 / c2))) + c3)**2


x = np.linspace(-10, 10, 50)
y = np.linspace(-10, 10, 50)
print(x)
XX, YY = np.meshgrid(x, y)

P = func(XX, YY)
p = Pinky(P=P, extent=[-10, 10, -10, 10])
sampled_points = p.sample(1000)

ax = plt.subplot(111)
plt.scatter(XX, YY)
plt.scatter(*sampled_points.T)

height = rt * np.sqrt(1. - ecc**2)
ellipse = mpatches.Ellipse(
    xy=(0., 0.), width=2. * rt, height=2. * height,
    facecolor='None', edgecolor='black', linewidth=2,
    transform=ax.transData, zorder=6)
ax.add_patch(ellipse)
plt.xlim(-11, 11)
plt.ylim(-11, 11)
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/12770968/91775775-8a48ff80-ebb1-11ea-8284-daa8989a2a6c.png)

**Comment by Gabriel-p** [comment]
Nice! Thank you very much!

BTW this is the **only** Python code I could find for a quick and easy 2D inverse transform sampling, and I looked *everywhere*. Don't mean to put any pressure on you :D
